# Generated by Django 3.2.6 on 2021-08-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DLP_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='patter',
            new_name='pattern',
        ),
    ]
